#!/usr/bin/env bash
# render-secrets-yaml.sh — CONTROL-NODE render of the ec2-instance-setup
# secrets.yaml contract from the gopass stores.
#
# WHY: ec2-instance-setup used to read the operator's rendered dotfiles out of
# $HOME (~/.local_configs, ~/.audeering_configs, ~/.aws/*, minio.cfg), which
# only exist if you replicate THIS machine's gopass + dotfiles machinery — so
# nobody else on the team could run the playbook. That repo now defines ONE
# explicit contract (its secrets.yaml.example) and renders the box's secret
# files from it. This script is the PRIVATE half: it fills that contract from
# gopass so the operator never types a credential by hand.
#
#   gopass (control node) -> secrets.yaml (0600, gitignored) -> playbook -> box
#
# A teammate needs NONE of this: they copy secrets.yaml.example, paste their own
# tokens, and run the playbook. This script is a convenience for whoever already
# keeps the credentials in gopass — the contract is the interface, not this file.
#
# Usage:
#   ./render-secrets-yaml.sh                  # -> the ec2 repo's secrets.yaml
#   ./render-secrets-yaml.sh --output PATH    # somewhere else
#   ./render-secrets-yaml.sh --print-missing  # just report coverage, write nothing
#
# Exits non-zero if the REQUIRED gitlab token is missing. Optional entries that
# are absent are reported by NAME and left empty, so the playbook skips those
# features instead of rendering broken config. Never prints a secret value.
# Requires gopass + the GPG key (i.e. the control node). Idempotent.
set -uo pipefail

EC2_REPO="${EC2_REPO:-$HOME/work/research/research/iva/aws/ec2-instance-setup}"
OUT="${OUT:-$EC2_REPO/secrets.yaml}"
PRINT_ONLY=0

while [ $# -gt 0 ]; do
  case "$1" in
    --output) OUT="${2:?--output needs a path}"; shift 2 ;;
    --print-missing) PRINT_ONLY=1; shift ;;
    -h|--help) sed -n '2,30p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

say()  { echo "== render-secrets-yaml: $*"; }
warn() { echo "!! render-secrets-yaml: $*" >&2; }
die()  { warn "$*"; exit 1; }

# gopass is a personal install; probe the usual rootless locations.
if ! command -v gopass >/dev/null 2>&1; then
  for d in "$HOME/go/bin" "$HOME/.local/bin"; do
    [ -x "$d/gopass" ] && { export PATH="$d:$PATH"; break; }
  done
fi
command -v gopass >/dev/null 2>&1 || die "gopass not found (control node only)"

missing=()

# get <gopass-path> -> value on stdout, or empty. Records misses by NAME.
get() {
  local v
  v="$(gopass show -o "$1" 2>/dev/null)" || v=""
  [ -n "$v" ] || missing+=("$1")
  printf '%s' "$v"
}

# yq <value> -> a safely single-quoted YAML scalar ('' escapes an inner quote).
yq() { printf "'%s'" "${1//\'/\'\'}"; }

# ---------------------------------------------------------------- gather ----
# REQUIRED: without this the box cannot clone the audeering repos.
GITLAB_TOKEN_V="$(get aud/api/gitlab/gitlab_api_token)"
HF_V="$(get personal/huggingface/api_key)"

# AWS profiles: name | gopass dir under aud/iva/aws | region
AWS_PROFILES=(
  "default|credentials|us-east-1"
  "audEERING-CodeArtifact|codeartifact|eu-central-1"
  "audEERING-data|audrepo|eu-north-1"
)
# audb/audmodel S3 auth: host | gopass dir under aud/iva/aws | comment
MINIO_HOSTS=(
  "s3.dualstack.eu-north-1.amazonaws.com|minio-data|audb-internal, audmodel-internal, audmodel-public"
  "s3.dualstack.eu-central-1.amazonaws.com|audrepo|audeering-audmodel-private"
)
# Model/service API keys: yaml key | gopass path
API_KEYS=(
  "anthropic|personal/api/anthropic/anthropic_api_key_personal"
  "openai|aud/api/openai/openai_api_key"
  "deepgram|personal/api/deepgram/main"
  "speechmatics|audeering/iva/speechmatics/api-key"
  "nvidia|audeering/iva/nvidia/api-key"
  "gradium|personal/api/gradium/gradium_api_key"
)

[ -n "$GITLAB_TOKEN_V" ] \
  || die "REQUIRED aud/api/gitlab/gitlab_api_token is empty/missing — cannot render"

# ----------------------------------------------------------------- render ---
tmp="$(mktemp)" || die "mktemp failed"
chmod 600 "$tmp"
trap 'rm -f "$tmp"' EXIT

{
  echo "# secrets.yaml — GENERATED by myfiles/dotfiles/provision/render-secrets-yaml.sh"
  echo "# from the gopass stores on the control node. DO NOT EDIT BY HAND and NEVER"
  echo "# COMMIT: it is gitignored and holds live credentials. Re-render after any"
  echo "# credential rotation. Schema + the hand-edit path: secrets.yaml.example."
  echo
  echo "gitlab:"
  echo "  api_token: $(yq "$GITLAB_TOKEN_V")"
  echo "  host: gitlab.audeering.com"
  echo
  echo "huggingface:"
  echo "  token: $(yq "$HF_V")"
  echo
  echo "aws:"
  echo "  profiles:"
  for entry in "${AWS_PROFILES[@]}"; do
    IFS='|' read -r name dir region <<< "$entry"
    akid="$(get "aud/iva/aws/$dir/aws_access_key_id")"
    secret="$(get "aud/iva/aws/$dir/aws_secret_access_key")"
    echo "    - name: $(yq "$name")"
    echo "      access_key_id: $(yq "$akid")"
    echo "      secret_access_key: $(yq "$secret")"
    echo "      region: $(yq "$region")"
  done
  echo
  echo "audb_minio:"
  for entry in "${MINIO_HOSTS[@]}"; do
    IFS='|' read -r host dir comment <<< "$entry"
    ak="$(get "aud/iva/aws/$dir/aws_access_key_id")"
    sk="$(get "aud/iva/aws/$dir/aws_secret_access_key")"
    echo "  - host: $(yq "$host")"
    echo "    comment: $(yq "$comment")"
    echo "    access_key: $(yq "$ak")"
    echo "    secret_key: $(yq "$sk")"
  done
  echo
  echo "api_keys:"
  for entry in "${API_KEYS[@]}"; do
    IFS='|' read -r key path <<< "$entry"
    echo "  $key: $(yq "$(get "$path")")"
  done
} > "$tmp"

# --------------------------------------------------------------- validate ---
# Catch a quoting bug here rather than on the box: the file must be valid YAML
# and the required key must have survived the render.
if command -v python3 >/dev/null 2>&1; then
  python3 - "$tmp" <<'PY' || die "the rendered YAML is invalid — not writing $OUT"
import sys, yaml
d = yaml.safe_load(open(sys.argv[1])) or {}
tok = (d.get("gitlab") or {}).get("api_token") or ""
assert tok and "CHANGEME" not in tok, "gitlab.api_token missing in rendered YAML"
print(f"   YAML valid: {len(d)} top-level blocks, gitlab.api_token present")
PY
else
  warn "python3 not found — skipped the YAML validation step"
fi

if [ "${#missing[@]}" -gt 0 ]; then
  warn "empty/missing gopass entries (left empty; the playbook skips those features):"
  printf '!!   %s\n' "${missing[@]}" >&2
fi

if [ "$PRINT_ONLY" = 1 ]; then
  say "--print-missing: nothing written"
  exit 0
fi

[ -d "$(dirname "$OUT")" ] || die "output dir does not exist: $(dirname "$OUT")"
if [ -e "$OUT" ]; then
  cp "$OUT" "$OUT.bak.$(date +%Y%m%d-%H%M%S)" || warn "backup of $OUT failed"
  chmod 600 "$OUT.bak."* 2>/dev/null || true
fi
install -m 600 "$tmp" "$OUT" || die "could not write $OUT"
say "wrote $OUT (0600, gitignored)"
say "next: cd $EC2_REPO && make playbook"
